vich_uploader:
    db_driver: orm
    # configuration qui fait fonctionner le bundle
    
    mappings:
       products:
            uri_prefix: '%app.path.product_images%'
                        # paramètre conteneur du chemin de base
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
                                # Les images téléchargées sont stockées dans ce répertoire